/* BMAK + BOEE glossary – short-handles and technical terms */
window.GLOSSARY = {
  /* ---- Single-letter / short symbols (matched case-sensitively) ---- */
  "Y": "Output / income (real GDP in the model).",
  "Yn": "Natural output: medium-run equilibrium level of output when u = u_n.",
  "Y_D": "Disposable income: Y − T (income after taxes).",
  "YD": "Disposable income: Y − T.",
  "G": "Government spending (exogenous in the basic model).",
  "T": "Taxes (lump-sum in the basic model).",
  "C": "Consumption. Typically C = c0 + c1 Y_D.",
  "I": "Investment. Often I = b0 + b1 Y − b2 r (accelerator + interest sensitivity).",
  "M": "Nominal money stock (or money supply).",
  "P": "Price level.",
  "H": "High-powered money / monetary base: currency + bank reserves.",
  "W": "Nominal wage.",
  "NX": "Net exports = Exports − Imports.",
  "N": "Employment (number of workers).",
  "u": "Unemployment rate.",
  "u_n": "Natural rate of unemployment: the rate at which WS and PS intersect.",
  "z": "Catch-all factor shifting the wage-setting relation (benefits, unions, etc.). Higher z raises u_n.",

  /* ---- Greek letters ---- */
  "alpha": "Often the slope of the Phillips curve: how strongly inflation responds to the unemployment gap.",
  "beta": "Generic preference / discount parameter, or a coefficient in behavioural equations / regression.",
  "mu": "Markup of price over marginal cost. Higher markup lowers the real wage in PS and raises u_n.",
  "pi": "Inflation rate (percentage change in the price level).",

  /* ---- Core model names ---- */
  "IS": "IS curve: combinations of Y and i (or r) that clear the goods market. Downward-sloping.",
  "LM": "LM curve: combinations of Y and i that clear the money market. Upward-sloping (or horizontal in a liquidity trap).",
  "WS": "Wage-setting relation: real wage workers require as a function of unemployment (and other factors z).",
  "PS": "Price-setting relation: real wage implied by firms' markup over cost.",

  /* ---- Longer phrases (case-insensitive) ---- */
  "natural rate": "Natural rate of unemployment (u_n): medium-run equilibrium u where WS meets PS.",
  "natural output": "Yn: output consistent with u = u_n.",
  "markup": "Markup of price over cost. Higher markup lowers real wage in PS and raises u_n.",
  "MPC": "Marginal propensity to consume: fraction of an extra unit of disposable income that is consumed.",
  "MPS": "Marginal propensity to save: 1 − MPC.",
  "multiplier": "Goods-market multiplier: 1/(1−c1) in the simple model.",
  "crowding-out": "Fiscal expansion raises the interest rate, which reduces private investment, partially offsetting the stimulus.",
  "liquidity trap": "Interest rate at (or near) the zero lower bound so conventional monetary policy cannot lower i further.",
  "Phillips curve": "Relation between inflation and unemployment. Accelerationist form under adaptive expectations.",
  "medium run": "Horizon at which prices and wages have adjusted so the economy is back at u_n (and Yn).",
  "Solow": "Solow growth model: capital accumulation, steady-state k*, long-run growth driven by technical progress.",
  "Fisher": "Fisher relation: i ≈ r + expected inflation. Nominal rate = real rate + expected inflation.",

  /* ---- BOEE / Econometrics ---- */
  "CEF": "Conditional Expectation Function: E[y|x], the mean of y given the value(s) of x. Central object of interest in regression.",
  "Conditional Expectation Function": "E[y|x]: average value of the outcome given the covariates. What regression aims to model.",
  "LIE": "Law of Iterated Expectations: E[Y] = E[E[Y|X]]. The overall average equals the average of the conditional averages.",
  "Law of Iterated Expectations": "E[Y] = E[E[Y|X]]. Used constantly to prove properties of the regression error.",
  "OLS": "Ordinary Least Squares: the estimator that minimises the sum of squared residuals. Most common way to estimate a linear regression.",
  "residual": "Difference between the observed outcome and the fitted value: e-hat = y - y-hat. By construction residuals sum to zero and are orthogonal to the regressors when an intercept is present.",
  "exogeneity": "Mean independence: E[e|x] = 0. Key assumption that makes the linear CEF the best linear predictor and underpins unbiasedness/consistency of OLS.",
  "mean independence": "E[e|x] = 0. The error has mean zero for every value of x.",
  "attenuation bias": "Bias toward zero of the OLS slope when the regressor is measured with classical additive measurement error.",
  "multicollinearity": "High correlation among regressors. Inflates standard errors (imprecise estimates) but does not by itself cause bias or inconsistency.",
  "perfect multicollinearity": "One regressor is an exact linear combination of the others. X'X is singular and OLS is not uniquely defined (dummy-variable trap is the classic example).",
  "omitted variable bias": "Bias that arises when a relevant variable that is correlated with an included regressor is left out of the regression.",
  "OVB": "Omitted-variable bias.",
  "heteroskedasticity": "Non-constant conditional variance of the error: Var(e|x) is not the same for all x. Does not bias OLS point estimates but invalidates classical standard errors.",
  "robust standard errors": "Heteroskedasticity-consistent (HC) standard errors that remain valid when Var(e|x) is not constant. Obtained in R via vcovHC / coeftest.",
  "HC": "Heteroskedasticity-consistent (robust) variance estimator.",
  "vcovHC": "R function (sandwich package) that computes a heteroskedasticity-robust variance-covariance matrix for an lm object.",
  "coeftest": "R function (lmtest) that produces coefficient tests; often used with vcov = vcovHC for robust inference.",
  "t-statistic": "t = (estimate - hypothesized value) / standard error. Used for single-coefficient tests.",
  "F-statistic": "Statistic for joint hypotheses (several coefficients restricted simultaneously). Large values reject the joint null.",
  "consistency": "plim beta-hat = beta. As the sample size grows the estimator converges in probability to the true parameter.",
  "plim": "Probability limit. The value an estimator converges to in probability as n goes to infinity.",
  "CLT": "Central Limit Theorem. Under regularity conditions the sampling distribution of the OLS estimator is approximately normal in large samples, justifying normal critical values for t- and F-tests.",
  "marginal effect": "Partial derivative of the conditional mean with respect to a regressor. In a linear model it equals the slope; in a quadratic it equals beta1 + 2*beta2*x and therefore depends on the level of x.",
  "interaction term": "Product of two regressors (e.g. x*D). Allows the slope of one variable to differ according to the value of the other.",
  "saturated model": "Regression with a full set of mutually exclusive group dummies (and no continuous regressors). Fitted values recover the group-specific means of y.",
  "dummy-variable trap": "Perfect multicollinearity that arises when a full set of group dummies is included together with an intercept. Solution: omit one category (the reference group).",
  "lm": "R function for linear models / OLS: lm(y ~ x1 + x2).",
  "I(x^2)": "R formula syntax that forces ordinary arithmetic so a quadratic term can be included: lm(y ~ x + I(x^2))."
};
