/* BMAK glossary – short-handles and technical terms */
window.GLOSSARY = {
  "IS": "IS curve: combinations of Y and i (or r) that clear the goods market (Investment = Saving). Downward-sloping.",
  "LM": "LM curve: combinations of Y and i that clear the money market (Liquidity preference = Money supply). Upward-sloping (or horizontal under interest-rate targeting).",
  "WS": "Wage-setting relation: real wage desired by workers, decreasing in unemployment u and increasing in factors z (benefits, unions, etc.).",
  "PS": "Price-setting relation: real wage consistent with firms' markup. W/P = 1/(1+μ). Horizontal in the basic model.",
  "WS-PS": "Wage-setting / price-setting diagram that determines the natural rate of unemployment u_n and the medium-run real wage.",
  "u_n": "Natural rate of unemployment: the unemployment rate at which WS and PS intersect; medium-run equilibrium unemployment.",
  "natural rate": "Natural rate of unemployment (u_n): medium-run equilibrium u where real wage from WS equals real wage from PS.",
  "μ": "Markup of price over marginal cost. Higher μ lowers the real wage in PS and raises u_n.",
  "markup": "Markup (μ) of price over cost. Higher markup → lower real wage in PS → higher natural unemployment.",
  "z": "Catch-all factor shifting the wage-setting relation (unemployment benefits, employment protection, union power, etc.). Higher z raises u_n.",
  "MPC": "Marginal propensity to consume: the fraction of an extra unit of disposable income that is consumed (c₁).",
  "MPS": "Marginal propensity to save: 1 − MPC.",
  "multiplier": "Goods-market multiplier: 1/(1−c₁) in the simple model; larger with an accelerator, smaller with import leakage.",
  "crowding-out": "Fiscal expansion raises the interest rate, which reduces private investment (and/or NX), partially offsetting the stimulus.",
  "liquidity trap": "Situation in which the interest rate is at (or near) the zero lower bound so that conventional monetary policy cannot lower i further; LM is effectively horizontal.",
  "UIP": "Uncovered interest parity: i = i* + expected depreciation. Links domestic and foreign interest rates via expected exchange-rate changes.",
  "NX": "Net exports = Exports − Imports. Depends negatively on domestic Y and on the real exchange rate ε (under the usual definition).",
  "ε": "Real exchange rate (competitiveness). A rise in ε is a real appreciation (domestic goods more expensive relative to foreign goods).",
  "Marshall-Lerner": "Condition that a real depreciation improves the trade balance: sum of export and import price elasticities > 1.",
  "impossible trinity": "Trilemma: a country cannot simultaneously have a fixed exchange rate, free capital mobility, and an independent monetary policy.",
  "trilemma": "Same as the impossible trinity: fixed exchange rate + free capital flows + independent monetary policy cannot all hold at once.",
  "Phillips curve": "Relation between inflation (or wage inflation) and unemployment. Modern accelerationist version: Δπ = −α(u − u_n) under adaptive expectations.",
  "PC": "Phillips curve: link between inflation and the unemployment gap. Accelerationist under adaptive expectations.",
  "accelerationist": "Under adaptive expectations the Phillips curve is in terms of the change in inflation: keeping u below u_n makes inflation rise continuously.",
  "adaptive expectations": "Expected inflation equals last period's actual inflation (πᵉ_t = π_{t−1}). Leads to an accelerationist Phillips curve.",
  "anchored expectations": "Expected inflation is tied to a credible target (πᵉ = π-bar). The Phillips curve becomes a stable level relation rather than accelerationist.",
  "medium run": "Horizon at which prices and wages have adjusted so that the economy is back at the natural rate of unemployment (and natural output).",
  "natural output": "Yn: the level of output consistent with u = u_n (medium-run equilibrium output).",
  "Yn": "Natural output: medium-run equilibrium level of output when u = u_n.",
  "risk premium": "Extra spread x that borrowers pay over the policy rate; the relevant rate for investment is often r = i + x.",
  "money multiplier": "Ratio of broad money to high-powered money: (1+c)/(c+θ), where c is the currency-deposit ratio and θ the reserve ratio.",
  "high-powered money": "H (or monetary base): currency in circulation plus bank reserves. Controlled by the central bank.",
  "Solow": "Solow growth model: capital accumulation, steady-state capital intensity k*, and long-run growth driven by technical progress g.",
  "golden rule": "Golden-rule capital stock: the steady-state k that maximises consumption per effective worker.",
  "Fisher": "Fisher relation: i ≈ r + πᵉ. Nominal interest rate equals real rate plus expected inflation.",
  "IS-LM": "IS-LM model: simultaneous equilibrium in goods (IS) and money (LM) markets; determines short-run Y and i.",
  "IS-LM-PC": "IS-LM plus Phillips curve: framework for short-run and medium-run dynamics of output, interest rates and inflation."
};
