window.QUESTIONS = (window.QUESTIONS || []).concat([
  {id:"m01",type:"numerical",topic:"money",examRelevance:4,source:"HW2",question:"M^D = Y(0.2−0.8i), Y=5000. Money demand at i=0.01?",answer:960,tolerance:0,explanation:"5000×0.192 = 960."},
  {id:"m02",type:"numerical",topic:"money",examRelevance:4,source:"HW2",question:"Same, money demand at i=0.05?",answer:800,tolerance:0,explanation:"5000×0.16 = 800."},
  {id:"m03",type:"mcq",topic:"money",examRelevance:4,source:"HW2",question:"What increases desired money holdings?",options:["Rise in interest rate","Fall in interest rate","Fall in income","None"],answer:1,explanation:"Money demand decreases in i, increases in Y."},
  {id:"m04",type:"numerical",topic:"money",examRelevance:4,source:"HW2",question:"θ=0.1, no currency, M^D=$Y(0.8−4i), H=100, $Y=5000. Equilibrium i in %?",answer:15,tolerance:0,explanation:"0.1×5000×(0.8−4i)=100 → i=0.15 → 15%."},
  {id:"m05",type:"truefalse",topic:"money",examRelevance:4,source:"HW2",question:"To raise equilibrium money demand the CB should lower the interest rate.",answer:true,explanation:"Money demand is decreasing in i."},
  {id:"m06",type:"numerical",topic:"money",examRelevance:4,source:"Derivative of m04",question:"Same money market as m04 but θ=0.2. New equilibrium i in %?",answer:17.5,tolerance:0.1,explanation:"0.2×5000×(0.8−4i)=100 → 0.8−4i=0.1 → i=0.175 → 17.5%."},
  {id:"m07",type:"numerical",topic:"money",examRelevance:4,source:"Core",question:"Money multiplier when currency-deposit ratio c=0.2 and reserve ratio θ=0.1?",answer:4,tolerance:0,explanation:"(1+c)/(c+θ)=1.2/0.3=4."},
  {id:"m08",type:"truefalse",topic:"money",examRelevance:4,source:"Core",question:"An increase in the reserve ratio θ reduces the money multiplier.",answer:true,explanation:"Money multiplier = (1+c)/(c+θ) falls when θ rises."},
  {id:"m09",type:"mcq",topic:"money",examRelevance:4,source:"Core",question:"When the central bank sets the interest rate, the money supply is:",options:["Exogenous","Endogenous","Always equal to H","Fixed by the government"],answer:1,explanation:"H (or M) adjusts endogenously so the money market clears at the chosen i."},
  {id:"m10",type:"numerical",topic:"money",examRelevance:4,source:"Derivative",question:"M^D = Y(0.25 − i), Y=4000, M^s=800. Equilibrium i?",answer:0.05,tolerance:0.001,explanation:"4000(0.25−i)=800 → 0.25−i=0.2 → i=0.05."},
  {id:"m11",type:"numerical",topic:"money",examRelevance:4,source:"Multiplier",question:"Currency-deposit ratio c=0.25, reserve ratio θ=0.1. Money multiplier?",answer:3.571,tolerance:0.01,explanation:"(1+c)/(c+θ)=1.25/0.35≈3.571."},
  {id:"m12",type:"numerical",topic:"money",examRelevance:4,source:"Derivative",question:"Same ratios. If high-powered money H=200, equilibrium money supply M?",answer:714.29,tolerance:0.5,explanation:"M = multiplier × H ≈ 3.571×200 ≈ 714.29."},
  {id:"m13",type:"numerical",topic:"money",examRelevance:4,source:"Derivative",question:"M^D = Y(0.3 − 2i), Y=2000, M^s=400. Equilibrium i?",answer:0.05,tolerance:0.001,explanation:"2000(0.3−2i)=400 → 0.3−2i=0.2 → 2i=0.1 → i=0.05."}
]);
