window.QUESTIONS = (window.QUESTIONS || []).concat([
  {id:"l01",type:"truefalse",topic:"labor",examRelevance:5,source:"Core",question:"The natural rate of unemployment is determined by the intersection of the wage-setting and price-setting relations.",answer:true,explanation:"WS-PS intersection defines u_n."},
  {id:"l02",type:"mcq",topic:"labor",examRelevance:5,source:"Core",question:"A higher markup μ shifts the PS relation and causes natural unemployment to:",options:["Fall","Rise","Stay the same","Become zero"],answer:1,explanation:"Higher μ → lower real wage in PS → higher u_n."},
  {id:"l03",type:"mcq",topic:"labor",examRelevance:5,source:"Core",question:"An increase in unemployment benefits (higher z) tends to:",options:["Lower u_n","Raise u_n","Leave u_n unchanged","Raise the real wage in the medium run only"],answer:1,explanation:"WS shifts up → higher u_n."},
  {id:"l04",type:"truefalse",topic:"labor",examRelevance:4,source:"Core",question:"In the medium run the real wage is determined by the markup: W/P = 1/(1+μ).",answer:true,explanation:"PS is horizontal at 1/(1+μ)."},
  {id:"l05",type:"numerical",topic:"labor",examRelevance:5,source:"WS-PS",question:"WS: W/P = 1 − u + 0.05. PS: W/P = 0.8. Natural rate u_n?",answer:0.25,tolerance:0.01,explanation:"1−u+0.05=0.8 → 1.05−u=0.8 → u_n=0.25."},
  {id:"l06",type:"truefalse",topic:"labor",examRelevance:4,source:"Core",question:"Efficiency-wage considerations help explain why the WS relation slopes downward in unemployment.",answer:true,explanation:"Higher unemployment disciplines wage demands."},
  {id:"l07",type:"mcq",topic:"labor",examRelevance:5,source:"Core",question:"Natural output Yn corresponds to:",options:["u = 0","u = u_n","Full employment in the Keynesian sense","The golden-rule capital stock"],answer:1,explanation:"Yn is the output level consistent with u_n."},
  {id:"l08",type:"truefalse",topic:"labor",examRelevance:4,source:"Core",question:"The labor-market equilibrium (WS-PS) is independent of the price level P in the basic model.",answer:true,explanation:"Both relations are in real-wage space."},
  {id:"l09",type:"mcq",topic:"labor",examRelevance:5,source:"Core",question:"A reduction in the markup μ (e.g. more competition) leads in the medium run to:",options:["Higher u_n","Lower u_n and higher real wage","Unchanged u_n","Lower natural output"],answer:1,explanation:"PS shifts up → lower u_n, higher real wage."}
]);
