window.QUESTIONS = (window.QUESTIONS || []).concat([
  {id:"p01",type:"truefalse",topic:"pc",examRelevance:5,source:"Lecture 08",question:"When u < u_n, inflation tends to rise (accelerate) under adaptive expectations.",answer:true,explanation:"π_t − πᵉ_t = −β(u_t − u_n). If u < u_n, π > πᵉ."},
  {id:"p02",type:"mcq",topic:"pc",examRelevance:5,source:"Core",question:"If CB keeps u permanently below u_n (adaptive expectations), inflation:",options:["Stabilizes higher","Keeps accelerating","Falls to zero","Unaffected"],answer:1,explanation:"Accelerationist PC → continuous rise in inflation."},
  {id:"p03",type:"truefalse",topic:"pc",examRelevance:5,source:"Lecture 08",question:"The original Phillips curve was a level relation; modern versions with adaptive expectations are accelerationist.",answer:true,explanation:"Original: π = −α(u−u_n). Adaptive θ=1: Δπ = −α(u−u_n)."},
  {id:"p04",type:"mcq",topic:"pc",examRelevance:5,source:"Core",question:"When expectations are fully anchored (πᵉ = π-bar), the Phillips curve is:",options:["Vertical","A stable negative level relation","Accelerationist","Horizontal"],answer:1,explanation:"π − π-bar = −α(u−u_n) → classic tradeoff."},
  {id:"p05",type:"truefalse",topic:"pc",examRelevance:5,source:"Lecture 08",question:"Higher wage indexation increases the sensitivity of inflation changes to the unemployment gap.",answer:true,explanation:"Indexation raises the coefficient on the unemployment gap."},
  {id:"p06",type:"numerical",topic:"pc",examRelevance:5,source:"Derivative",question:"Accelerationist PC: Δπ = −0.5 (u − 0.06). If u=0.04, by how many percentage points does inflation change this period?",answer:1,tolerance:0,explanation:"Δπ = −0.5(0.04−0.06)= +0.01 → +1 pp."},
  {id:"p07",type:"numerical",topic:"pc",examRelevance:5,source:"Derivative",question:"Same PC. What unemployment rate keeps inflation constant?",answer:0.06,tolerance:0,explanation:"u = u_n = 0.06."},
  {id:"p08",type:"truefalse",topic:"pc",examRelevance:5,source:"Core",question:"Under fully adaptive expectations there is no long-run trade-off between inflation and unemployment.",answer:true,explanation:"Long-run PC is vertical at u_n."},
  {id:"p09",type:"mcq",topic:"pc",examRelevance:5,source:"Core",question:"An oil-price shock that raises the markup shifts the Phillips curve:",options:["Down","Up","Not at all","Only IS"],answer:1,explanation:"Higher inflation for any given unemployment rate."},
  {id:"p10",type:"truefalse",topic:"pc",examRelevance:5,source:"Core",question:"If expectations are perfectly anchored, a temporary rise in unemployment permanently lowers the inflation rate.",answer:false,explanation:"With anchored expectations the PC is a level relation; once u returns to u_n, inflation returns to the anchored level."},
  {id:"p11",type:"numerical",topic:"pc",examRelevance:5,source:"Numerical",question:"Accelerationist PC: Δπ = −0.4 (u − 0.05). If u=0.07, by how many percentage points does inflation change?",answer:-0.8,tolerance:0.01,explanation:"Δπ = −0.4×(0.07−0.05)= −0.4×0.02= −0.008 → −0.8 pp."},
  {id:"p12",type:"numerical",topic:"pc",examRelevance:5,source:"Derivative",question:"Same PC. What u keeps Δπ = 0?",answer:0.05,tolerance:0,explanation:"u = u_n = 0.05."},
  {id:"p13",type:"numerical",topic:"pc",examRelevance:5,source:"Derivative",question:"Δπ = −0.5 (u − 0.06). If the central bank wants Δπ = −0.01 (disinflation of 1 pp), what u is required?",answer:0.08,tolerance:0.001,explanation:"−0.01 = −0.5(u−0.06) → 0.02 = u−0.06 → u=0.08."},
  {id:"p14",type:"truefalse",topic:"pc",examRelevance:4,source:"Core",question:"Anchored expectations make the short-run tradeoff between inflation and unemployment more stable.",answer:true,explanation:"With πᵉ fixed at the target, the PC is a stable level relation rather than accelerationist."}
]);
