window.QUESTIONS = (window.QUESTIONS || []).concat([
  {id:"med01",type:"truefalse",topic:"medium",examRelevance:5,source:"Lecture 09",question:"After a positive demand shock the economy returns to natural output in the medium run, but inflation is higher if policy does not tighten.",answer:true,explanation:"Higher expected inflation shifts PC; restoring u_n requires higher real rates."},
  {id:"med02",type:"mcq",topic:"medium",examRelevance:5,source:"Core",question:"In the medium run, monetary policy is:",options:["Neutral for output but affects inflation","Affects both output and inflation permanently","Neutral for both","Affects only the real interest rate"],answer:0,explanation:"Output returns to natural level; inflation is determined by monetary policy."},
  {id:"med03",type:"truefalse",topic:"medium",examRelevance:5,source:"Core",question:"In the IS-LM-PC model a permanent increase in G raises natural output.",answer:false,explanation:"Natural output is supply-side (WS-PS). Demand shocks affect only prices/inflation in the medium run."},
  {id:"med04",type:"mcq",topic:"medium",examRelevance:5,source:"Core",question:"After a permanent rise in G, in the medium run the real interest rate is:",options:["Higher","Lower","Unchanged","Determined only by money supply"],answer:0,explanation:"Higher G requires higher r to keep Y at natural level (crowding-out of I)."},
  {id:"med05",type:"truefalse",topic:"medium",examRelevance:5,source:"Core",question:"In the medium run a permanent increase in the money supply raises the price level proportionally and leaves real variables unchanged.",answer:true,explanation:"Monetary neutrality / classical dichotomy."},
  {id:"med06",type:"mcq",topic:"medium",examRelevance:5,source:"Core",question:"An adverse supply shock (higher μ) in the medium run produces:",options:["Higher natural unemployment and lower real wage","Lower natural unemployment","Unchanged u_n","Higher output"],answer:0,explanation:"PS shifts down → higher u_n, lower real wage."},
  {id:"med07",type:"truefalse",topic:"medium",examRelevance:5,source:"Core",question:"The medium-run equilibrium is characterized by u = u_n and π constant (or equal to expected inflation).",answer:true,explanation:"Definition of medium-run equilibrium in the IS-LM-PC model."},
  {id:"med08",type:"mcq",topic:"medium",examRelevance:5,source:"Policy chain",question:"A permanent fiscal expansion (higher G). In the short run Y rises and i rises. In the medium run, to return to natural output the central bank must:",options:["Raise the policy rate further","Lower the policy rate","Keep the policy rate unchanged","Increase the money supply"],answer:0,explanation:"Higher G requires a higher natural real rate; CB must accommodate the higher r_n."},
  {id:"med09",type:"truefalse",topic:"medium",examRelevance:5,source:"Policy chain",question:"After a permanent increase in G, medium-run output returns to the original natural level while the real interest rate is permanently higher.",answer:true,explanation:"Crowding-out of investment; Y_n unchanged, r_n higher."},
  {id:"med10",type:"mcq",topic:"medium",examRelevance:5,source:"Policy chain",question:"An adverse supply shock raises the markup. In the medium run we observe:",options:["Higher u_n, lower real wage, higher natural real rate","Lower u_n, higher real wage","Unchanged natural rate","Higher natural output"],answer:0,explanation:"PS shifts down → higher u_n and lower real wage; IS at lower Y_n may imply higher r_n."},
  {id:"pe11",type:"mcq",topic:"medium",examRelevance:5,source:"Policy effectiveness",question:"In the medium run, a permanent monetary expansion:",options:["Permanently raises Y","Permanently lowers the real interest rate","Raises the price level proportionally and leaves real variables unchanged","Raises natural output"],answer:2,explanation:"Monetary neutrality: only nominal variables change in the medium run."},
  {id:"pe12",type:"mcq",topic:"medium",examRelevance:5,source:"Policy effectiveness",question:"In the medium run, a permanent fiscal expansion (higher G):",options:["Permanently raises Y","Leaves the real interest rate unchanged","Permanently raises the natural real interest rate and crowds out investment","Has no real effects at all"],answer:2,explanation:"Y returns to Yn, but composition changes: higher r_n crowds out I (or NX)."},
  {id:"pe13",type:"truefalse",topic:"medium",examRelevance:5,source:"Policy effectiveness",question:"Even though monetary policy is neutral for output in the medium run, it remains the main tool for controlling inflation.",answer:true,explanation:"Inflation is a monetary phenomenon in the medium run."}
]);
