window.QUESTIONS = (window.QUESTIONS || []).concat([
  {id:"gr01",type:"truefalse",topic:"growth",examRelevance:3,source:"Core Solow",question:"In the Solow model, a higher saving rate permanently raises the growth rate of output per worker.",answer:false,explanation:"Higher s raises the level of capital and output per worker; long-run growth is determined by technical progress."},
  {id:"gr02",type:"mcq",topic:"growth",examRelevance:3,source:"Core Solow",question:"In the Solow steady state, output per effective worker is constant when:",options:["s increases","n or δ rises","sf(k) = (δ+n+g)k","The capital stock grows at rate n"],answer:2,explanation:"Investment equals break-even investment."},
  {id:"gr03",type:"truefalse",topic:"growth",examRelevance:3,source:"Core",question:"Countries with higher investment rates tend to have higher levels of output per worker, consistent with the Solow model.",answer:true,explanation:"Higher s → higher steady-state k and y."},
  {id:"gr04",type:"numerical",topic:"growth",examRelevance:3,source:"Core",question:"Solow: s=0.3, δ+n+g=0.08, f(k)=k^{0.5}. Steady-state capital per effective worker k*?",answer:14.0625,tolerance:0.01,explanation:"0.3 √k = 0.08 k → √k = 0.3/0.08 = 3.75 → k* = 3.75² = 14.0625."},
  {id:"gr05",type:"truefalse",topic:"growth",examRelevance:3,source:"Core",question:"In the Solow model with technical progress, steady-state growth of output per worker equals the rate of technical progress g.",answer:true,explanation:"y grows at rate g."},
  {id:"gr06",type:"mcq",topic:"growth",examRelevance:3,source:"Core",question:"An increase in the depreciation rate δ leads to a new steady state with:",options:["Higher k* and y*","Lower k* and y*","Unchanged k*","Higher growth rate of y"],answer:1,explanation:"Higher break-even investment → lower steady-state capital intensity."},
  {id:"gr07",type:"truefalse",topic:"growth",examRelevance:3,source:"Core",question:"The golden-rule capital stock maximizes steady-state consumption per effective worker.",answer:true,explanation:"Definition of the golden rule."},
  {id:"gr08",type:"numerical",topic:"growth",examRelevance:3,source:"Solow",question:"Solow: s=0.25, δ=0.04, n=0.01, g=0.02, f(k)=√k. Steady-state k*?",answer:12.755,tolerance:0.01,explanation:"s√k=(δ+n+g)k → 0.25√k=0.07k → √k=0.25/0.07≈3.571 → k*=(3.571)²≈12.755."},
  {id:"gr09",type:"numerical",topic:"growth",examRelevance:3,source:"Solow",question:"Same Solow parameters. Steady-state output per effective worker y*?",answer:3.571,tolerance:0.01,explanation:"y*=√k*≈3.571."},
  {id:"gr10",type:"numerical",topic:"growth",examRelevance:3,source:"Derivative",question:"Solow: s=0.3, δ=0.05, n=0.02, g=0.03, f(k)=√k. Steady-state k*?",answer:9,tolerance:0,explanation:"0.3√k = 0.1 k → √k = 3 → k*=9."},
  {id:"gr11",type:"numerical",topic:"growth",examRelevance:3,source:"Derivative",question:"Same as gr10. If s rises to 0.4, new k*?",answer:16,tolerance:0,explanation:"0.4√k=0.1k → √k=4 → k*=16."},
  {id:"gr12",type:"numerical",topic:"growth",examRelevance:3,source:"Golden rule",question:"Solow: f(k)=√k, δ+n+g=0.08. Golden-rule capital stock k_gold (MPK=δ+n+g)?",answer:39.0625,tolerance:0.1,explanation:"MPK=0.5/√k = 0.08 → √k=0.5/0.08=6.25 → k_gold=39.0625."},
  {id:"gr13",type:"numerical",topic:"growth",examRelevance:3,source:"Golden rule",question:"Same parameters. Steady-state consumption per effective worker at the golden rule?",answer:3.125,tolerance:0.01,explanation:"y=6.25, (δ+n+g)k=3.125, c=y−(δ+n+g)k=3.125."},
  {id:"gr14",type:"truefalse",topic:"growth",examRelevance:3,source:"Core",question:"If the current steady-state capital stock is below the golden-rule level, an increase in the saving rate raises steady-state consumption.",answer:true,explanation:"Moving toward the golden rule increases c*."},
  {id:"gr15",type:"mcq",topic:"growth",examRelevance:3,source:"Core",question:"In the Solow model, a permanent rise in the rate of technical progress g eventually leads to:",options:["Higher growth of y and lower k*","Higher growth of y and higher k*","Lower growth of y","No change in the growth rate of y"],answer:0,explanation:"Higher g raises long-run growth of y but also raises break-even investment → lower k*."}
]);
