window.QUESTIONS = (window.QUESTIONS || []).concat([
  {id:"i01",type:"truefalse",topic:"islm",examRelevance:5,source:"Core",question:"An increase in G shifts IS right and raises both Y and i.",answer:true,explanation:"Higher demand at any i -> IS right -> higher Y and i (partial crowding-out)."},
  {id:"i02",type:"truefalse",topic:"islm",examRelevance:5,source:"Core",question:"An increase in money supply shifts LM down/right, lowering i and raising Y.",answer:true,explanation:"More real balances require lower i."},
  {id:"i03",type:"mcq",topic:"islm",examRelevance:5,source:"Core",question:"Which most likely shifts IS right?",options:["Rise in money supply","Cut in taxes T","Rise in reserve requirement","Fall in consumer confidence"],answer:1,explanation:"Lower T raises disposable income and C."},
  {id:"i04",type:"mcq",topic:"islm",examRelevance:5,source:"Core",question:"Crowding-out refers to:",options:["G reducing private investment via higher i","Taxes reducing C","Money supply reducing i","Imports reducing NX"],answer:0,explanation:"Higher i reduces interest-sensitive investment."},
  {id:"i05",type:"mcq",topic:"islm",examRelevance:5,source:"Core",question:"With horizontal LM (liquidity trap), fiscal policy is:",options:["Ineffective","Fully effective (no crowding-out)","Weaker than usual","Only effective with monetary expansion"],answer:1,explanation:"i does not rise -> no crowding-out."},
  {id:"i06",type:"truefalse",topic:"islm",examRelevance:5,source:"Core",question:"IS is downward-sloping because higher i reduces investment and therefore equilibrium Y.",answer:true,explanation:"Higher i -> lower I -> lower demand -> lower Y."},
  {id:"i07",type:"mcq",topic:"islm",examRelevance:5,source:"Core",question:"What makes the IS multiplier larger than 1/(1-c1)?",options:["Money market","Investment depending positively on Y (accelerator)","Taxes","CB setting i"],answer:1,explanation:"Multiplier becomes 1/(1-c1-b1)."},
  {id:"i08",type:"truefalse",topic:"islm",examRelevance:5,source:"Core",question:"In the modern treatment the LM curve is often drawn as horizontal because the central bank sets the interest rate.",answer:true,explanation:"CB chooses i; money supply adjusts endogenously."},
  {id:"i09",type:"numerical",topic:"islm",examRelevance:5,source:"HW3-style",question:"IS: Y = 1200 - 30i (i in %). LM: Y = 800 + 20i. Equilibrium Y?",answer:960,tolerance:0,explanation:"1200-30i = 800+20i -> 400=50i -> i=8; Y=1200-240=960."},
  {id:"i10",type:"numerical",topic:"islm",examRelevance:5,source:"HW3-style",question:"Same IS-LM. Equilibrium interest rate i (percent)?",answer:8,tolerance:0,explanation:"i=8."},
  {id:"i11",type:"numerical",topic:"islm",examRelevance:5,source:"Derivative",question:"IS becomes Y=1350-30i (fiscal expansion). New equilibrium Y (same LM)?",answer:1020,tolerance:0,explanation:"1350-30i=800+20i -> 550=50i -> i=11; Y=800+220=1020."},
  {id:"i12",type:"numerical",topic:"islm",examRelevance:5,source:"New system",question:"IS: Y = 1500 - 40i (i in %). LM: Y = 900 + 30i. Equilibrium i (in %)?",answer:8.571,tolerance:0.01,explanation:"1500-40i = 900+30i -> 600=70i -> i approx 8.571."},
  {id:"i13",type:"numerical",topic:"islm",examRelevance:5,source:"New system",question:"Same IS-LM. Equilibrium Y?",answer:1157.14,tolerance:0.5,explanation:"Y = 1500 - 40*(600/70) approx 1157.14."},
  {id:"i14",type:"truefalse",topic:"islm",examRelevance:5,source:"Core",question:"An increase in the risk premium shifts the IS curve left for a given policy rate.",answer:true,explanation:"Higher borrowing costs -> lower I -> IS left."},
  {id:"i15",type:"mcq",topic:"islm",examRelevance:5,source:"Core",question:"If the risk premium rises one-for-one with a cut in the policy rate, the effect of the monetary expansion on Y is:",options:["Fully effective","Partially effective","Zero","Amplified"],answer:2,explanation:"Borrowing rate unchanged -> investment unchanged -> no effect on Y."},
  {id:"i16",type:"truefalse",topic:"islm",examRelevance:5,source:"Core",question:"When LM is horizontal, fiscal expansion raises Y by the full goods-market multiplier.",answer:true,explanation:"No rise in i -> no crowding-out."},
  {id:"i17",type:"mcq",topic:"islm",examRelevance:5,source:"Core",question:"A simultaneous rise in G and rise in money supply typically leads to:",options:["Higher Y, ambiguous i","Lower Y, higher i","Ambiguous Y, higher i","Lower Y, lower i"],answer:0,explanation:"Both policies raise Y; effect on i is ambiguous."}
]);
