window.QUESTIONS = (window.QUESTIONS || []).concat([
  {id:"l01",type:"truefalse",topic:"labor",examRelevance:5,source:"Lecture 07",question:"Natural unemployment is the rate at which real wage from WS equals real wage from PS.",answer:true,explanation:"WS: W/P = F(u,z). PS: W/P = 1/(1+μ). Intersection = u_n."},
  {id:"l02",type:"truefalse",topic:"labor",examRelevance:5,source:"Lecture 07",question:"Higher markup μ or higher z (e.g. more generous benefits) raises the natural rate u_n.",answer:true,explanation:"Higher μ shifts PS down; higher z shifts WS up → higher u_n."},
  {id:"l03",type:"mcq",topic:"labor",examRelevance:5,source:"Lecture 07",question:"An increase in unemployment benefits (higher z) leads to:",options:["Higher natural unemployment","Lower natural unemployment","No change in u_n","Lower medium-run real wage"],answer:0,explanation:"WS shifts up → intersection with PS at higher u_n."},
  {id:"l04",type:"truefalse",topic:"labor",examRelevance:5,source:"Lecture 07",question:"In the medium run the real wage is determined solely by the markup (W/P = 1/(1+μ)).",answer:true,explanation:"PS is horizontal; WS adjusts via unemployment until the real wage equals 1/(1+μ)."},
  {id:"l05",type:"mcq",topic:"labor",examRelevance:5,source:"Core",question:"A decrease in the markup μ (more competition) leads to:",options:["Higher natural unemployment","Lower natural unemployment and higher real wage","No change in u_n","Lower real wage"],answer:1,explanation:"PS shifts up → lower u_n and higher real wage."},
  {id:"l06",type:"truefalse",topic:"labor",examRelevance:5,source:"Core",question:"Stronger employment protection (higher z) raises the natural rate of unemployment.",answer:true,explanation:"Higher z shifts WS up."},
  {id:"l07",type:"mcq",topic:"labor",examRelevance:4,source:"Core",question:"Natural employment is determined by:",options:["Aggregate demand","Intersection of WS and PS","Monetary policy","The position of the IS curve"],answer:1,explanation:"Supply-side labor-market equilibrium."},
  {id:"l08",type:"truefalse",topic:"labor",examRelevance:5,source:"Core",question:"In the medium run, a rise in unemployment benefits lowers the real wage.",answer:false,explanation:"Real wage is still 1/(1+μ); higher z only raises u_n."},
  {id:"l09",type:"truefalse",topic:"labor",examRelevance:4,source:"Core",question:"In the short run the actual unemployment rate can differ from the natural rate; in the medium run it returns to u_n.",answer:true,explanation:"Medium-run adjustment occurs via price/wage dynamics and the Phillips curve."}
]);
