/* Auto-generated by scripts/generate-manifest.js – do not edit by hand */
window.QUESTION_MANIFEST = {
  "generated": "2026-07-22T02:40:00.000Z",
  "subjects": [
    {
      "id": "BMAK-macro",
      "label": "BMAK · macro",
      "files": [
        "01-goods.js",
        "02-money.js",
        "03-islm.js",
        "04-labor.js",
        "05-pc.js",
        "06-medium.js",
        "07-growth.js",
        "08-open-mf.js",
        "09-accounts.js",
        "10-gaps-focused.js",
        "11-final-polish.js"
      ]
    },
    {
      "id": "BOEE-Econometrics",
      "label": "BOEE · Econometrics",
      "files": [
        "01-cef-concepts.js",
        "02-ols-mechanics.js",
        "03-nonlinearities.js",
        "04-hypothesis-testing.js",
        "05-multivariate-and-gaps.js",
        "06-r-basics.js"
      ]
    },
    {
      "id": "BWIN-wirtschaftsinformatik",
      "label": "BWIN · wirtschaftsinformatik",
      "files": [
        "01-grundlagen.js",
        "02-epk.js",
        "03-erm.js",
        "04-sql.js",
        "05-python.js"
      ]
    }
  ]
};
