/* Auto-generated by scripts/generate-manifest.js – do not edit by hand */
window.QUESTION_MANIFEST = {
  "generated": "2026-07-22T00:00:00.000Z",
  "subjects": [
    {
      "id": "BMAK-macro",
      "label": "BMAK · macro",
      "files": [
        "01-goods.js",
        "02-money.js",
        "03-islm.js",
        "04-labor.js",
        "05-pc.js",
        "06-medium.js",
        "07-growth.js",
        "08-open-mf.js",
        "09-accounts.js",
        "10-gaps-focused.js",
        "11-final-polish.js"
      ]
    }
  ]
};
